-- ====================================================================
-- 🏢 한페이지(Hanpage) 공식 홈페이지 Supabase SQL 초기 세팅 스크립트
-- ====================================================================
-- 이 SQL 스크립트는 한페이지 공식 웹사이트의 실시간 교육 문의 접수와
-- 관리자 활동 갤러리 미디어 업로드 및 동적 관리를 위한 데이터베이스 구축용입니다.
-- Supabase 대시보드 -> [SQL Editor] -> [New Query]에 붙여넣고 실행(Run)하세요.

-- --------------------------------------------------------------------
-- 📞 1. 실시간 교육 문의 테이블 (inquiries) 생성
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    name TEXT NOT NULL,
    school_name TEXT NOT NULL,
    email TEXT,                              -- 이메일 주소 (추가)
    phone TEXT,                              -- 연락처 번호 (추가)
    program_interest TEXT NOT NULL,
    content TEXT NOT NULL,
    status TEXT DEFAULT '접수'::text NOT NULL -- '접수', '답변완료', '보류' 등
);

-- RLS(Row Level Security) 설정 활성화
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;

-- 🛡️ inquiries 테이블 보안 정책(Policies)
-- 정책 A: 외부 방문자가 실시간으로 문의를 등록(Insert)할 수 있도록 허용
CREATE POLICY "방문자 실시간 문의 등록 허용" 
ON public.inquiries 
FOR INSERT 
WITH CHECK (true);

-- 정책 B: 인증된 관리자(Authenticated)만 문의 목록을 조회(Select), 수정(Update), 삭제(Delete) 가능
CREATE POLICY "관리자 문의 조회 허용" 
ON public.inquiries 
FOR SELECT 
TO authenticated 
USING (true);

CREATE POLICY "관리자 문의 수정 허용" 
ON public.inquiries 
FOR UPDATE 
TO authenticated 
USING (true);

CREATE POLICY "관리자 문의 삭제 허용" 
ON public.inquiries 
FOR DELETE 
TO authenticated 
USING (true);


-- --------------------------------------------------------------------
-- 📸 2. 활동 갤러리 테이블 (gallery) 생성
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.gallery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    media_url TEXT NOT NULL,
    media_type TEXT DEFAULT 'image'::text NOT NULL -- 'image' 또는 'video'
);

-- RLS(Row Level Security) 설정 활성화
ALTER TABLE public.gallery ENABLE ROW LEVEL SECURITY;

-- 🛡️ gallery 테이블 보안 정책(Policies)
-- 정책 A: 외부 방문자를 포함한 모든 사람(Public)이 갤러리를 조회(Select)할 수 있도록 허용
CREATE POLICY "갤러리 전체 공개 조회 허용" 
ON public.gallery 
FOR SELECT 
USING (true);

-- 정책 B: 인증된 관리자(Authenticated)만 갤러리 업로드(Insert), 수정(Update), 삭제(Delete) 가능
CREATE POLICY "관리자 갤러리 등록 허용" 
ON public.gallery 
FOR INSERT 
TO authenticated 
WITH CHECK (true);

CREATE POLICY "관리자 갤러리 수정 허용" 
ON public.gallery 
FOR UPDATE 
TO authenticated 
USING (true);

CREATE POLICY "관리자 갤러리 삭제 허용" 
ON public.gallery 
FOR DELETE 
TO authenticated 
USING (true);


-- --------------------------------------------------------------------
-- 📁 3. Supabase Storage (hanpage-media) 권한 안내 및 설정
-- --------------------------------------------------------------------
-- 💡 Storage 버킷은 Supabase 대시보드 UI를 통해 직접 생성하는 것을 권장합니다.
-- [방법 안내]:
--   1. Supabase 대시보드 왼쪽 메뉴의 [Storage] 클릭
--   2. [+ New Bucket] 클릭 후 버킷 이름에 `hanpage-media` 입력
--   3. "Public bucket" 토글 스위치를 활성화(ON) 상태로 켜주세요. (이미지 주소 노출용)
--   4. [Save]를 눌러 버킷을 저장하세요.
--
-- 만약 Storage RLS 정책이 자동으로 생성되지 않거나 수동으로 설정이 필요할 경우, 
-- 아래 쿼리를 수행하여 스토리지 버킷의 물리적 보안 규격을 일괄 적용하세요.

-- hanpage-media 스토리지 접근을 위한 RLS 설정 (필요시 실행)
-- A. 퍼블릭 누구나 미디어를 다운로드 및 조회 가능하도록 설정
CREATE POLICY "스토리지 미디어 전체 다운로드 및 조회 허용"
ON storage.objects FOR SELECT
USING ( bucket_id = 'hanpage-media' );

-- B. 인증된 관리자(Authenticated)만 스토리지에 업로드, 수정, 삭제 가능하도록 설정
CREATE POLICY "관리자 스토리지 미디어 등록 허용"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK ( bucket_id = 'hanpage-media' );

CREATE POLICY "관리자 스토리지 미디어 수정 허용"
ON storage.objects FOR UPDATE
TO authenticated
USING ( bucket_id = 'hanpage-media' );

CREATE POLICY "관리자 스토리지 미디어 삭제 허용"
ON storage.objects FOR DELETE
TO authenticated
USING ( bucket_id = 'hanpage-media' );

-- ====================================================================
-- 🎉 데이터베이스 세팅 완료!
-- ====================================================================
